#!/usr/bin/bash
set -e

source ${HOME}/.dbus.env

method=$1
plugin=$2
screen=$3
object=$4
arg="$5"

slash=''
if [[ -n "${object}" ]]; then
  slash='/'
fi

echo dbus-send --print-reply --type=method_call --dest=org.freedesktop.compiz /org/freedesktop/compiz/${plugin}/${screen}${slash}${object} org.freedesktop.compiz.${method} ${arg}
dbus-send --print-reply --type=method_call --dest=org.freedesktop.compiz /org/freedesktop/compiz/${plugin}/${screen}${slash}${object} org.freedesktop.compiz.${method} ${arg}
